---
title: "Migratory behaviour in birds: an attempt of classification across all species"
author: "Alison Eyres & Susanne Fritz"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Migratory behaviour in birds: an attempt of classification across all species}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

If you use this dataset, please cite Eyres et al. (2017); this paper also contains essential information of the rationale behind the dataset, although it used version 1 of the dataset (which only differed in not classifying extinct species and some minor mistakes fixed since). Here we provide a methods overview for the classification of migratory behaviour in birds, which is valid for both versions of the dataset. The dataset focuses on seasonal migration, i.e. movements causing an individual adult bird to be found in different locations over the course of one year, excluding everyday routine movements (e.g. foraging movements) and one-way dispersal movements by juveniles (natal dispersal) or adults (Newton 2008). Types or categories of migratory behaviour and different subcategories were recorded and classified with the Handbook of the Birds of the World (del Hoyo 1992-2013 and updates on the Handbook of the Birds of the World Alive website www.hbw.com, accessed until September 2016).

### Main categories and subcategories of migratory behaviour within species

We distinguished these main categories of migratory behaviour (for examples, see Table A1 in Eyres et al. 2017), following Newton (2008):

-	**Directional migration.** Individuals make regular return movements that are clearly seasonal and directional, i.e. they move every year from specific breeding grounds to specific non-breeding locations. Movements have a clear latitudinal or longitudinal directionality. These include typical long-distance migration where entire populations move between geographically separate areas.
-	**Dispersive migration.** Individuals make regular post-breeding movements in any direction from breeding sites, i.e. movements are clearly seasonal but have no consistent latitudinal or longitudinal directionality. These include movements typical of many seabirds as these disperse seasonally from their breeding colonies on islands or coasts to roam widely over winter foraging grounds at sea. They also include typical altitudinal movements made consistently in vertical direction but not in one geographical direction. 
-	**Nomadism.** Individuals make irregular movements from one area to another, residing for a time wherever food is temporarily plentiful, and breeding if possible. Movements are not seasonal and not directional, because the areas successively occupied may lie in various directions from one another and can vary from year to year. 
-	**Residency.** Individuals are sedentary and do not make major regular or irregular movements.
-	**Unknown migratory behaviour.** There is not enough information to classify migratory behaviour as above.

Initially, we classified intraspecific variation in movement behaviours for each species, so that all different population- and individual-level movements were recorded in a presence-absence matrix of categories and subcategories. The categories are given above; each of the three categories designating movement behaviour (directional migratory, dispersive migratory, and nomadic) was further subdivided into the three different subcategories full, partial, and local. The subcategories were primarily intended to capture the degree of intraspecific variation, as each movement behaviour can occur as follows:
-	across all individuals and populations of a species (fully migratory or fully nomadic species),
-	just in some populations or parts of populations (partially migratory or partially nomadic species), or
-	at a local scale, i.e. only in or over some areas that constitute a small proportion of a species’ distribution (locally migratory or locally nomadic species).

Note that the distance of migratory movements was disregarded in our classification, except that very short-distance movements were classified as subcategory local (see Table S1 for examples). 
Several of the main categories were applied to a species if categories were each classified as only partially or locally in a given category, to capture the behaviours exhibited by each population (e.g. partially migratory species are often also partially resident). Species classified as fully within one category of migratory behaviour (e.g. full directional migrants) could be also classified as locally within another migratory category (e.g. local dispersive migrant or locally nomadic), but not as partially within another category. If a type of migratory behaviour occurred partially in a species, we did not apply the subcategory “local” in the same main category even if the local behaviour applied to a different population; similarly, if “full” applied for a category, none of the other two subcategories (“partial” and “local”) were applied for the same main category. Note that under our classification, a species described as nomadic within one season (usually the non-breeding season) is not partially nomadic, because the behaviour occurs seasonally; instead, it is classified as partially migratory in the “dispersive migration” category.

Resident behaviour was only distinguished into the subcategories full or partial:

-	Fully resident species are those that show no migratory behaviour of any kind, or only show local migratory (directional and/or dispersive) or local nomadic behaviour.
-	Partially resident species are those with sedentary populations or parts of populations, i.e. they should also be classified as partially migratory (directional and/or dispersive) or partially nomadic.
The special cases of altitudinal migration and irruptive behaviour were additionally recorded in separate columns. A species was flagged in the altitudinal migration column of the dataset if some part of one or more populations performed seasonal altitudinal movements, which are usually dispersive rather than directional (Newton 2008). The occurrence of irruptions was flagged in a column independently of nearly all other columns, so that species in any behavioural category could show irruptive behaviour except for fully resident species.

A comment column was used to enter a brief summary of the descriptions of movements from the Handbook of the Birds of the World, which can therefore differ from the framework used here in their use of definitions to describe migratory behaviour (see e.g. the note on partially nomadic vs. dispersive behaviour above; examples for abbreviated comments and descriptions are in Table A1 of Eyres et al. 2017). We used both the family and species accounts originally from the printed book versions (del Hoyo 1992-2013), but updated most with the Handbook of the Birds of the World Alive webpage (www.hbw.com, accessed April 2016 – November 2017). In general, the mapped geographic distributions also supplied in the Handbook corroborated our categorization of species from the species accounts, but sometimes text descriptions did not match information apparent in the map, which was then mentioned in the migratory status comments.

### Species-level classification of migratory behaviour

In a second step, we classified each species based on the available intraspecific data on movement behaviour. The final migratory behaviour for species with several “partial” subcategories was decided as consistently as possible by a single person for all species, on the basis of proportional representation of behaviours across different populations (see Table A1 in Eyres et al. 2017 for examples). In addition, there is an “uncertain” column in the dataset that was used to flag species where the decision among the main categories of behaviour was difficult because information was lacking to determine which category was predominant (e.g. they were classified as “partial” for more than one behaviour and from the description showed each behaviour to roughly equal extents; or the movement description indicated that movements or seasonal distributions were poorly or inadequately known).

In the special case of altitudinal migration, species that exclusively perform altitudinal migration within the breeding range were usually classified as species-level residents with “partial” subcategories applying for the “dispersive” and the “resident” category and the “altitudinal” column flagged; if the altitudinal migration caused the species’ distribution to have large distinct seasonal areas mapped, e.g. Himalayan birds migrating down and southwards into the adjacent lowlands, the species was classified as species-level dispersive with “partial” subcategories applying for the “dispersive” and the “resident” category and the “altitudinal” column flagged (see Phylloscopidae example species in Table A1, Eyres et al. 2017).

The “unknown” category of movement behaviour was only applied to very few species where migratory behaviour really was completely unclear, e.g. those only known from a few museum specimen, and the “uncertain” column was used to flag only cases where there was reason to doubt a particular classification as any of the main categories. For some species, the “movement” section in the Handbook only said “no information”, which was generally entered in the comment column. These species were usually mapped as resident in the Handbook itself and often had restricted ranges or were part of higher taxa consisting exclusively of residents; in these cases, species were classified as resident without flagging in the “uncertain” column (as any large-scale movement behaviour is highly unlikely for these species), and the comment “presumed resident” was added with a qualifier in brackets (e.g. “New Guinea” for species endemic to New Guinea, or “HBW map year-round only”). 

The database contains the full list of 10596 species as given by the IOC version 3.1 (Gill & Donsker 2012). In version 2, we also classified the movement behaviour of 155 extinct species; these are flagged in a “fully extinct” column, and were mostly species officially declared extinct, plus a few that have not been documented in decades but are listed as “critically endangered (possibly extinct)” (IUCN Red List at www.iucnredlist.com, accessed April-September 2016). Further, we used a “partially extinct” column to flag a further 49 species affected by the extinction of whole populations or across entire geographic entities (typically islands); this was to highlight that migratory behaviour of extinct populations for these species might be unknown or badly known, and might have been different from the extant populations used as the basis of our classification.

We also classified species as fully or partially marine, to highlight seabirds and waterbirds whose geographic distributions are fully or partially mapped at sea. Marine species were defined as spending most of their daily movements in marine environments, typically foraging in any marine habitat from tidal flats to pelagic or open sea, so that geographic distributions are mapped at sea (at least partially). Fully marine species were defined to also breed in marine environments, usually along coasts or on oceanic islands, and very little of their distribution was usually mapped on land. Partially marine species were defined as occurring seasonally in terrestrial or freshwater environments, so these may breed on land close to or far from the coast. There were 252 fully marine species and a further 117 partially marine species (numbers for version 2 of the dataset).

### Examples of detailed descriptions and how they were classified

Below, we give some examples of how descriptions of movements in the Handbook were interpreted in our database, and summarize the key parameters for each categorization. In general, if a behaviour was described as occurring “possibly”, “maybe”, “likely”, or similar, we added the description in the comment column but did not use the information for categorization; stronger words like “probably” or “apparently” were often used for categorization, but usually the uncertainty column was then flagged. Descriptions that were too vague (“migration / movements suspected / suggested” or “may show migration / movements”) were recorded in the comments but disregarded for categorization (but note that “some seasonal / dispersive / nomadic / irregular movements” was recorded as locally dispersive or locally nomadic). This rule did not apply to the description of resident behaviour, as in many cases the movement text only said “apparently”, “presumably”, or “probably” resident or sedentary; if there was no further information given, the species was classified as resident.


**Directional migration:** regular seasonality of movements and clear directionality of seasonal movement.

-	Full: all individuals (or virtually all individuals) of the species migrate seasonally between distinct breeding and non-breeding areas. Should usually have separate areas on the map, unless distribution not well known. Described usually as “migratory” or “fully migratory”.
-	Partial: only part of a population or only some populations migrate seasonally between distinct breeding and non-breeding areas. Usually have separate areas on the map, but not if migratory populations winter (or breed) in areas where other populations breed (or winter, or both). Usually described as “partially migratory”, but can be described as “somewhat migratory” or even “mostly / mainly / largely resident / sedentary” if there is a directional migration described for at least one sizable population or for a substantial part of the global population. Can also be described as “migratory” in the special case of seabirds that disperse to some degree and year-round around the breeding colonies (usually oceanic islands or rocky coasts), but with overall directional movement tendencies in a specific season (these were classified as partially migratory and partially dispersive). Usually not classified if seasonal movements clearly depend on weather (typically following rains) or resource availability, as these are not usually directional and therefore classified as dispersive migration.
-	Local: individuals migrate directionally only in some regions that constitute a small proportion of a species’ distribution, and movements are at a relatively local scale. Can have separate areas on the map but these should be quite a small proportion of the whole range; usually no separate areas on the map. Has to be described as “local / short-range / limited seasonal migration / movements” with clear seasonal occurrence in defined regions, not just as “local / short-range / limited movements following water / resource availability”.

**Dispersive migration:** regular seasonality of movements and no clear directionality of seasonal movement.

-	Full: all individuals (or virtually all individuals) of the species migrate seasonally, but breeding and non-breeding areas are usually not fully distinct or are just adjacent to each other; often, non-breeding areas are mapped around or close to year-round or breeding areas, and in some cases only year-round areas are mapped. Described usually as “dispersive”, “extensive / marked post-breeding dispersal”, “extensive / marked seasonal wandering” or as “migratory” with description of the dispersive behaviour (e.g. “disperses along coasts in non-breeding season”, “seasonal dispersive movements following rains / resource availability”). Altitudinal migrants (described as “altitudinal migration”, “seasonal altitudinal movements”, “regular elevational shifts” etc.) were classified as fully dispersive in the rare cases where separate breeding and non-breeding areas were mapped, but movements should be regularly seasonal and not be described as occurring only occasionally or in extreme weather. Fully dispersive behaviour also occurs in species that breed on or around freshwater and then disperse to coasts and winter on estuaries or at sea.

-	Partial: only part of a population or only some populations migrate seasonally, with breeding and non-breeding areas usually not fully distinct or just adjacent to each other for even just the migratory individuals or populations. As with full dispersive migration, non-breeding areas are mapped around or close to year-round or breeding areas, and in many cases only year-round areas are mapped (unless species also shows partial directional migration in other populations). Described as “partially dispersive”, “extensive post-breeding dispersal”, or “partially migratory” with description of the seasonal dispersive behaviour (e.g. “disperses along coasts in non-breeding season”, “seasonal movements following rains / resource availability”, “seasonal extensive wandering”, etc.); can also be described as “partially nomadic” or “with irregular dispersion” if the nomadic or dispersive behaviour only occurs in one season (usually “nomadic in the non-breeding season”). Partial dispersive behaviour was classified for most altitudinal migrants (including altitudinal migration within the breeding range) if these did not have separately mapped non-breeding areas, as well as for most seabirds, which usually have separately mapped breeding colonies and non-breeding distributions; dispersive behaviour was categorized based on expressions as described above for fully dispersive migrants but occurring in only part of the populations or individuals. Can be described as “somewhat dispersive” or even “mostly / mainly / largely resident / sedentary” if there is dispersive migration described for at least one sizable population or for a substantial part of the global population.

-	Local: individuals disperse seasonally only in some regions that constitute a small proportion of a species’ distribution, and dispersive movements are at a relatively local scale. Usually no separate areas on the map (unless also showing partial directional migration in other areas), or some small non-breeding areas adjacent to larger year-round areas. Has to be described as “locally dispersive” with clear seasonal dispersive behaviour, “local / marked post-breeding dispersal”, “local / short-range / limited dispersive movements”, “local / short-range / limited seasonal movements following water / resource availability”, “local seasonal habitat shifts”, “some wandering / dispersive movements / seasonal movements / local movements”, or with “regular / seasonal / local wandering”.

**Nomadism:** irregular movements that are not seasonal and no clear directionality of movement.

-	Full: all individuals (or virtually all individuals) of the species make irregular movements from one area to another, residing for a time wherever food is temporarily plentiful, and breeding if possible. Usually no seasonally distinct areas mapped. Has to be described as “nomadic” or “fully nomadic”, or as wandering without seasonal pattern, and usually breeds any time of the year.
-	Partial: only part of a population or only some populations make irregular movements. Can have seasonally distinct areas mapped if also partially migratory. Can be described as “partially nomadic” (in the sense of not all populations being nomadic, but not in the temporal sense as in “nomadic during non-breeding season”), “partially showing irregular movements”, “partial irregular wandering”, or similar; can also be described as “mostly / mainly / largely resident / sedentary” if there is nomadic behaviour described for at least one sizable population or for a substantial part of the global population.
-	Local: individuals move nomadically only in some regions that constitute a small proportion of a species’ distribution, and nomadic movements are at a relatively local scale. No distinct areas mapped unless also partially migratory. Can be described as “locally nomadic”, “nomadic or irregular local / small-scale / limited movements related to water / resource availability”, “limited nomadism”, or “limited irregular wandering”.

### References

Del Hoyo, J. 1992-2013. Handbook of the Birds of the World. Vol. 1-16 and Special Vol. Lynx Edicions, Barcelona.

Eyres, A., Böhning-Gaese, K. & Fritz, S. A. 2017 Quantification of climatic niches in birds: adding the temporal dimension. Journal of Avian Biology online (doi: 10.1111/jav.01308)

Gill, F. & Donsker, D. 2012. IOC World Bird List (v. 3.1). Available at www.worldbirdnames.org. Accessed September 2012.

Newton, I. 2008. The Migration Ecology of Birds. Academic Press, London.
